-- MySQL Script generated by MySQL Workbench
-- Tue Sep 17 13:03:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema presto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema presto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `presto` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `presto` ;

-- -----------------------------------------------------
-- Table `presto`.`bus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presto`.`bus` (
  `bus_ID` INT NOT NULL,
  `bus_number` INT NOT NULL,
  `capacity` INT NOT NULL,
  `scanner_ID` INT NOT NULL,
  PRIMARY KEY (`bus_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `presto`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presto`.`customer` (
  `customer_ID` INT NOT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `presto`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presto`.`card` (
  `card_ID` INT NOT NULL,
  `customer_ID` INT NULL DEFAULT NULL,
  `balance` FLOAT(6,2) NULL DEFAULT NULL,
  PRIMARY KEY (`card_ID`),
  INDEX `customer_ID` (`customer_ID` ASC) VISIBLE,
  CONSTRAINT `card_ibfk_1`
    FOREIGN KEY (`customer_ID`)
    REFERENCES `presto`.`customer` (`customer_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `presto`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presto`.`location` (
  `location_ID` INT NOT NULL,
  `location_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`location_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `presto`.`operator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presto`.`operator` (
  `operator_ID` INT NOT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`operator_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `presto`.`route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presto`.`route` (
  `route_ID` INT NOT NULL,
  `route_name` VARCHAR(50) NULL DEFAULT NULL,
  `start_location` VARCHAR(50) NULL DEFAULT NULL,
  `end_location` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`route_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `presto`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presto`.`schedule` (
  `shchedule_ID` INT NOT NULL,
  `route_ID` INT NULL DEFAULT NULL,
  `bus_ID` INT NULL DEFAULT NULL,
  `operator_ID` INT NULL DEFAULT NULL,
  `scheduled_start_time` TIME NULL DEFAULT NULL,
  `scheduled_end_time` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`shchedule_ID`),
  INDEX `route_ID` (`route_ID` ASC) VISIBLE,
  INDEX `bus_ID` (`bus_ID` ASC) VISIBLE,
  INDEX `operator_ID` (`operator_ID` ASC) VISIBLE,
  CONSTRAINT `schedule_ibfk_1`
    FOREIGN KEY (`route_ID`)
    REFERENCES `presto`.`route` (`route_ID`),
  CONSTRAINT `schedule_ibfk_2`
    FOREIGN KEY (`bus_ID`)
    REFERENCES `presto`.`bus` (`bus_ID`),
  CONSTRAINT `schedule_ibfk_3`
    FOREIGN KEY (`operator_ID`)
    REFERENCES `presto`.`operator` (`operator_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `presto`.`trip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presto`.`trip` (
  `trip_ID` INT NOT NULL,
  `card_ID` INT NULL DEFAULT NULL,
  `bus_ID` INT NULL DEFAULT NULL,
  `route_ID` INT NULL DEFAULT NULL,
  `trip_start_time` TIME NULL DEFAULT NULL,
  `trip_end_time` TIME NULL DEFAULT NULL,
  `trip_cost` FLOAT(5,2) NULL DEFAULT NULL,
  `balance` FLOAT(6,2) NULL DEFAULT NULL,
  PRIMARY KEY (`trip_ID`),
  INDEX `card_ID` (`card_ID` ASC) VISIBLE,
  INDEX `bus_ID` (`bus_ID` ASC) VISIBLE,
  INDEX `route_ID` (`route_ID` ASC) VISIBLE,
  CONSTRAINT `trip_ibfk_1`
    FOREIGN KEY (`card_ID`)
    REFERENCES `presto`.`card` (`card_ID`),
  CONSTRAINT `trip_ibfk_2`
    FOREIGN KEY (`bus_ID`)
    REFERENCES `presto`.`bus` (`bus_ID`),
  CONSTRAINT `trip_ibfk_3`
    FOREIGN KEY (`route_ID`)
    REFERENCES `presto`.`route` (`route_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
